### ISSUE TITLE
Adding missing commons-lang dependency to Flow services

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow-services#164]
This is connected to a bug experienced after changes connected to this issue https://github.com/akvo/akvo-flow/issues/2160

We get an exception 

```
java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
	at org.waterforpeople.mapping.domain.QuestionAnswerStore.getDatapointNameValue(QuestionAnswerStore.java:207)
	at org.waterforpeople.mapping.dataexport.GraphicalSurveySummaryExporter.constructDisplayName(GraphicalSurveySummaryExporter.java:737)
	at org.waterforpeople.mapping.dataexport.GraphicalSurveySummaryExporter.writeInstanceData(GraphicalSurveySummaryExporter.java:605)
	at org.waterforpeople.mapping.dataexport.GraphicalSurveySummaryExporter.fetchAndWriteRawData(GraphicalSurveySummaryExporter.java:551)
	at org.waterforpeople.mapping.dataexport.GraphicalSurveySummaryExporter.export(GraphicalSurveySummaryExporter.java:397)
	at akvo.flow_services.exporter$export_report.invoke(exporter.clj:58)
	at akvo.flow_services.scheduler.ExportJob.execute(scheduler.clj:52)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
```

**Comment by janagombitova** [comment]
Is there something to test here?

**Comment by muloem** [comment]
Nope.  This is connected  to the display names so if those work fine then this is good to go!
