### ISSUE TITLE
Bulk upload fails if one of the zip files has no content

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow-services#58]
When uploading a set of zip files (surveyal) folder from the devices, if one of the zip files is empty the bulk uploader fails with the following exception.

```java
2014-12-09 09:54:12,603 services.akvoflow.org INFO [akvo.flow-services.uploader] - Bulk upload - path: /var/tmp/akvo/flow/uploads/63A3DF00-EE81-47F9-8ABA-8C1C83E0BE06/zip-content - bucket: waterforpeople - file: 
[QuartziteScheduler_Worker-4] ERROR org.quartz.core.JobRunShell - Job DEFAULT.63A3DF00-EE81-47F9-8ABA-8C1C83E0BE06 threw an unhandled Exception: 
java.util.zip.ZipException: zip file is empty
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:215)
	at java.util.zip.ZipFile.<init>(ZipFile.java:145)
	at java.util.zip.ZipFile.<init>(ZipFile.java:159)
	at sun.reflect.GeneratedConstructorAccessor563.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at clojure.lang.Reflector.invokeConstructor(Reflector.java:180)
	at akvo.flow_services.uploader$get_data.invoke(uploader.clj:121)
	at clojure.core$map$fn__4245.invoke(core.clj:2559)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:598)
	at clojure.core$next.invoke(core.clj:64)
	at clojure.core$concat$cat__3957$fn__3958.invoke(core.clj:701)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:484)
	at clojure.lang.RT.nthFrom(RT.java:848)
	at clojure.lang.RT.nth(RT.java:807)
	at clojure.core$distinct$step__4716$fn__4717$fn__4719.invoke(core.clj:4618)
	at clojure.core$distinct$step__4716$fn__4717.invoke(core.clj:4618)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:484)
	at clojure.core$seq.invoke(core.clj:133)
	at clojure.core$filter$fn__4264.invoke(core.clj:2595)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:598)
	at clojure.core$next.invoke(core.clj:64)
	at clojure.core.protocols$fn__6086.invoke(protocols.clj:146)
	at clojure.core.protocols$fn__6057$G__6052__6066.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
	at clojure.core.protocols$fn__6078.invoke(protocols.clj:54)
	at clojure.core.protocols$fn__6031$G__6026__6044.invoke(protocols.clj:13)
	at clojure.core$reduce.invoke(core.clj:6289)
	at clojure.core$group_by.invoke(core.clj:6602)
	at akvo.flow_services.uploader$bulk_survey.invoke(uploader.clj:148)
	at akvo.flow_services.uploader$bulk_upload.invoke(uploader.clj:170)
	at akvo.flow_services.scheduler.BulkUploadJob.execute(scheduler.clj:54)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
[QuartziteScheduler_Worker-4] ERROR org.quartz.core.ErrorLogger - Job (DEFAULT.63A3DF00-EE81-47F9-8ABA-8C1C83E0BE06 threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.util.zip.ZipException: zip file is empty]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:224)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: java.util.zip.ZipException: zip file is empty
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:215)
	at java.util.zip.ZipFile.<init>(ZipFile.java:145)
	at java.util.zip.ZipFile.<init>(ZipFile.java:159)
	at sun.reflect.GeneratedConstructorAccessor563.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at clojure.lang.Reflector.invokeConstructor(Reflector.java:180)
	at akvo.flow_services.uploader$get_data.invoke(uploader.clj:121)
	at clojure.core$map$fn__4245.invoke(core.clj:2559)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:598)
	at clojure.core$next.invoke(core.clj:64)
	at clojure.core$concat$cat__3957$fn__3958.invoke(core.clj:701)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:484)
	at clojure.lang.RT.nthFrom(RT.java:848)
	at clojure.lang.RT.nth(RT.java:807)
	at clojure.core$distinct$step__4716$fn__4717$fn__4719.invoke(core.clj:4618)
	at clojure.core$distinct$step__4716$fn__4717.invoke(core.clj:4618)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:484)
	at clojure.core$seq.invoke(core.clj:133)
	at clojure.core$filter$fn__4264.invoke(core.clj:2595)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:598)
	at clojure.core$next.invoke(core.clj:64)
	at clojure.core.protocols$fn__6086.invoke(protocols.clj:146)
	at clojure.core.protocols$fn__6057$G__6052__6066.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
	at clojure.core.protocols$fn__6078.invoke(protocols.clj:54)
	at clojure.core.protocols$fn__6031$G__6026__6044.invoke(protocols.clj:13)
	at clojure.core$reduce.invoke(core.clj:6289)
	at clojure.core$group_by.invoke(core.clj:6602)
	at akvo.flow_services.uploader$bulk_survey.invoke(uploader.clj:148)
	at akvo.flow_services.uploader$bulk_upload.invoke(uploader.clj:170)
	at akvo.flow_services.scheduler.BulkUploadJob.execute(scheduler.clj:54)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	... 1 more
```

**Comment by akvotender** [comment]
Assigned to [Tender discussion #5878](http://flowhelp.akvo.org/help/discussions/problems/5878-uploading-data).
